Fix TypeScript error (#1377)
It fixes the following Typescript error:

```
error TS2345: Argument of type '{ traceTurbolinks: true; turbo: boolean; }' is not assignable to parameter of type '{ traceTurbolinks: boolean; }'.
  Object literal may only specify known properties, and ''turbo'' does not exist in type '{ traceTurbolinks: boolean; }'.
```

That happens on this code:

```ts
ReactOnRails.setOptions({
  'traceTurbolinks': true,
  'turbo': true
})
```

Due to the fact that the `options` type is inferred by `DEFAULT_OPTIONS`.